

#pragma once

#include "CoreMinimal.h"
#include "Containers/Array.h"
#include "CommonTypes.h"


/**
 * Use this class to traverse paths that are generated by MazeGraph class.
 */
class PACMANUE_API Path final
{
public:
	
	TArrayTilesInline16& operator=(TArrayTilesInline16&& newPath);

	[[nodiscard]] TileCoordinate GetNextTile() const;

	[[nodiscard]] bool IsPathFullyTraversed() const;

	[[nodiscard]] bool IsEmpty() const;

	[[nodiscard]] u32 Length() const;

	[[nodiscard]] TileCoordinate PeekAhead(const u32 tileNumber) const;

	[[nodiscard]] u32 TotalNumEdgesTraversedUntilNow() const;

	[[nodiscard]] TileCoordinate GetLastTileInPath() const;

private:

	TArrayTilesInline16 _path{};
	mutable int32 _currentIndex{};
};
